# dockerfile.debian8
FROM debian:jessie
# Install Ansible
RUN apt-get install -y software-properties-common git
RUN apt-get update
RUN apt-get install -y ansible
# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
